jobs:
  create-infra:
    env:
      AZURE_REGISTRY_NAME: acralmpoc
      AZURE_RESOURCE_GROUP: rg-by-workflow-shared-dev-eus2-01
    name: Create Infra
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Container Registry
      run: 'az acr create --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_REGISTRY_NAME --sku Basic --admin-enabled true'
      #run: 'az acr delete --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_REGISTRY_NAME --yes'

name: Create ACR
on:
  workflow_dispatch:
    inputs:
