env:
  AZURE_WEBAPP_PACKAGE_PATH: ./build
  NODE_VERSION: 10.x
jobs:
  build-and-deploy:
    env:
      AZURE_APP_NAME: reactservice
      AZURE_APP_RUNTIME: NODE|12-lts
      DEPLOY_ENV: ${{matrix.azureenv}}
    environment: sandbox
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set the env variables according to env
      run: 'echo ${{matrix.azureenv}}

        echo $DEPLOY_ENV

        echo "AZURE_APP_ENV_NAME=${AZURE_APP_NAME}${DEPLOY_ENV}" >> $GITHUB_ENV

        '
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: '# Build and test the project, then

        # deploy to Azure Web App.

        npm install

        npm run build --if-present

        '
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_APP_ENV_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    strategy:
      matrix:
        azureenv:
        - sandbox
name: Build and deploy Raeact.js app to Azure Web App
on:
  workflow_dispatch:
    inputs:
